# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YWU5MzNkNDQ0OGVjNmY2OWNlOTcwOGZhYjM2MDM1ZGMwMDBmZDFkM2YzZTc1NjA1MGFhNjM3MWJjOTg4NzBjNjUwYjc4Y2E5OTUzMjBkOTJjODYzMWEzMDAyNWQ2NzgxYThmNjdiZTBmOTkwMDRkZmEwNzY5ZmVlYTkxMGIwNDM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
